dfinity/agent-rs

ic-agent/Cargo.toml, ic-agent/README.md, ic-types/Cargo.toml, ic-utils/Cargo.toml, ic-utils/README.md
=> chore: 0.1.2 of ic-types, and add metadata for cargo publish for others

.github/workflows/conventional-commits.yml, .github/workflows/ic-ref.yml, .github/workflows/netlify.yml, .github/workflows/test.yml
Basically the ic-ref workflow which uses a secret, the netlify which writes
a comment, and the conventional commits which needs comment as well.
Also made it better for forks to be able to run workflows.
=> ci: use pull_request_target for some workflows that need write access

ic-utils/src/interfaces/management_canister.rs, ic-utils/src/interfaces/management_canister/attributes.rs, ref-tests/tests/ic-ref.rs
It was a problem before because conversion to itself has an error type of `Infallible`.
=> fix: allow conversion from Compute/MemoryAllocation to itself

.github/workflows/ic-ref.yml, ic-agent/src/agent/agent_test.rs, ic-agent/src/agent/mod.rs, ic-utils/src/call.rs, ic-utils/src/canister.rs, ic-utils/src/interfaces/wallet.rs, ref-tests/Cargo.toml, ref-tests/src/universal_canister.rs, ref-tests/src/utils.rs, ref-tests/tests/ic-ref.rs, ref-tests/tests/integration.rs
This can happen either by passing raw bytes arguments (using the previous `call()`), or by building a Call and passing the Call in.
=> feat: call forwarding from a wallet canister

.github/workflows/ic-ref.yml
GitHub workflows dont have access to wallet-rs with a PAT.
=> ci: fix master

.github/workflows/ic-ref.yml
to match what’s in nixpkgs-20.09
(This is https://github.com/dfinity/agent-rs/pull/64 again, this time from within the repo, to test the workflow changes.)
=> chore: ic-ref CI: Use ghc-8.8.4

.github/workflows/ic-ref.yml
See https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/
The setup-haskell step, previous of versions 1.1.3, was not updated properly for the change. Just using a sliding v1.1 was apparently not enough to get the latest, so we force it.
=> ci: fix setup-haskell step

ic-agent/src/agent/agent_error.rs, ic-agent/src/agent/mod.rs, ic-agent/src/agent/replica_api.rs, ic-agent/src/agent/response_authentication.rs, ic-agent/src/agent/status.rs, ic-agent/src/lib.rs, ref-tests/src/utils.rs, ref-tests/tests/ic-ref.rs
Implements from doc:
- Checking BLS signature
- Fetching root key from /api/v1/status for dev instances
- Hard-coding Sodium key (**still need the actual key**).  (Note doc says this would be the Mercury key)
- Support for delegations 
See also companion PR [sdk #1197](https://github.com/dfinity/sdk/pull/1197)
=> feat: response authentication (certificate verification, root key lookup, delegations)

.github/workflows/ic-ref.yml, ic-utils/src/canister.rs, ic-utils/src/interfaces/management_canister.rs, ref-tests/Cargo.toml, ref-tests/tests/ic-ref.rs
This adds `deposit_cycles`, `provisional_create_canister_with_cycles`, `provisional_top_up_canister`, `raw_rand`, and updates `canister_status` to return a record
=> feat: add provisional, raw_rand, etc to mgmt canister

ic-agent/src/agent/agent_error.rs, ref-tests/tests/ic-ref.rs
Fixes https://github.com/dfinity/agent-rs/issues/91
For example, seen during a deploy:
```
± dfx ping ic
The replica returned an HTTP Error: Http Error: status 502 Bad Gateway,
content type "text/html",
content: [60, 104, 116, 109, 108, 62...]
```
=> feat: format any content-type: text as utf-8 text

.github/workflows/ic-ref.yml, ic-identity-hsm/src/hsm.rs, ref-tests/Cargo.toml, ref-tests/src/utils.rs, ref-tests/tests/ic-ref.rs
Adds a test phase that runs the ic-ref tests, but using the SoftHSM library to create identities rather than using basic identities.
This suite runs serially, because the SoftHSM library was panicking.
I also ran into trouble with two tests that create two identities.  The second call to `Ctx::new_and_initialize` panicked, so I made these two tests use a basic identity for the second identity.
This change surfaced an error related to slot ids.  The HSMs that I have used to date had slot index = slot id, but the SoftHSM library assigns different slot IDs.  So now we look up the slot id for the given slot index.
Updated to ic-ref 0.15.0, which added support for ECDSA keys.
Companion sdk PR: [PR-1316](https://github.com/dfinity/sdk/pull/1316)
Fixes …
=> test: Run tests using a software HSM

ic-agent/src/identity/anonymous.rs, ic-agent/src/identity/mod.rs
As of https://github.com/dfinity-lab/dfinity/pull/8248, we've started using `agent-rs`
for our system tests. One of our tests needs the `AnonymousIdentity`.
Making it public here to allow for that usage.
=> feat: Make `AnonymousIdentity` public

ic-agent/src/agent/agent_error.rs
The fixed message (`Could not reach the server`) may be hiding different underlying problems.  For example, I am seeing Clients (and therefore Agents) get stuck in a state where every request returns "channel closed"
=> feat: display request::Error message in AgentError

Cargo.toml, ic-agent/Cargo.toml, ic-agent/src/agent/agent_test.rs, ic-agent/src/identity/secp256k1.rs, ic-utils/Cargo.toml, ic-utils/src/interfaces.rs, ic-utils/src/interfaces/http_request.rs, icx-http-server/Cargo.toml, icx-http-server/README.md, icx-http-server/src/main.rs, ref-tests/Cargo.toml
The icx-http-server is used to create a HTTP server which redirects every
requests to /api to the replica directly, and every other requests to an
http_request query call on the canister itself.
For the moment the design doc is private but will be added in this repo soon.
=> feat: add an http-request interface and icx-http-server bin

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, README.md
Adds `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` (copied from vessel)
Fixes links and badges in `README.md`
=> docs: fix md links and badges

ic-agent/Cargo.toml, ic-agent/src/agent/agent_config.rs, ic-agent/src/agent/agent_error.rs, ic-agent/src/agent/agent_test.rs, ic-agent/src/agent/builder.rs, ic-agent/src/agent/http_facade.rs, ic-agent/src/agent/http_transport.rs, ic-agent/src/agent/mod.rs, ic-agent/src/agent/nonce.rs, ic-agent/src/lib.rs, ic-utils/src/call.rs, icx/Cargo.toml, icx/src/main.rs, ref-tests/tests/integration.rs
This whole PR is a breaking change if you're using the previous API. The best you can do is use the `reqwest` feature and ignore the deprecation warning for `with_url`.
=> feat: add a ReplicaV1Facade trait to communicate with the replica

ic-utils/src/canister.rs, ic-utils/src/interfaces/http_request.rs
Part of https://github.com/dfinity/dx-triage/issues/126
See also https://github.com/dfinity/sdk/pull/1512
=> feat: add http_request_next method (large asset support)

ic-agent/Cargo.toml, ic-agent/src/agent/mod.rs, ic-agent/src/lib.rs, ic-utils/Cargo.toml, ic-utils/src/call.rs, ic-utils/src/canister.rs, ic-utils/src/interfaces/management_canister.rs, ic-utils/src/interfaces/wallet.rs, icx-proxy/Cargo.toml, icx/Cargo.toml, icx/src/main.rs, ref-tests/Cargo.toml, ref-tests/src/utils.rs
* Revert #154, as it causes update call to wait forever.
* Remove unused crate `num-bigint`. It causes problems with simple_asn1.
When using `ic-agent` from my project, I get a compiler error
```
error[E0308]: mismatched types
--> /Users/chenyan/.cargo/registry/src/github.com-1ecc6299db9ec823/ic-agent-0.3.0/src/identity/secp256k1.rs:86:48
|
86 |     let ec_public_key_id = ObjectIdentifier(0, oid!(1, 2, 840, 10045, 2, 1));
|                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `simple_asn1::BigUint`, found struct `num_bigint::BigUint`
|
= note: expected struct `Vec<simple_asn1::BigUint>`
found struct `Vec<num_bigint::BigUint>`
= note: perhaps two different versions of crate `num_bigint` are being used?
= note: this error originates in a macro (in …
```
=> fix: revert garcon and remove unused bigint

ic-agent/src/agent/mod.rs, icx/README.md, icx/src/main.rs
Also added `--fetch-root-key` option to `icx`
To get the value for the root key, I ran this through a base64 decoder
```
-----BEGIN PUBLIC KEY-----
MIGCMB0GDSsGAQQBgtx8BQMBAgEGDCsGAQQBgtx8BQMCAQNhAIFMDm7HH6tYOwi9
gTc8JVw8NxsuhIY8mKTx4It0I10U+12cDNVG2WhfkToMCyzFNBWDv0tDkuRn25bW
W5u0y3FxEvhHLg1aTRRQX/10hLASkQkcX4e5iINGP5gJGguqrg==
-----END PUBLIC KEY-----
```
See also https://github.com/dfinity/sdk/pull/1643
=> feat: use hardcoded IC public key by default

ic-agent/src/agent/mod.rs, ic-agent/src/lib.rs
`fetch_root_key` should only be used sparingly when using a local
emulator or trusted replica. If the replica is untrusted but the
key is known, this adds a new `set_root_key` method to the agent to
override the root key.
This PR also clarifies the wording around the example to say that
this is not recommended.
=> feat: add a set_root_key and clarify docs

ic-agent/src/agent/mod.rs, ic-agent/src/agent/replica_api.rs, ic-agent/src/agent/response_authentication.rs, ic-agent/src/hash_tree.rs, ic-agent/src/hash_tree/hash_tree_tests.rs
This allows us to reduce memory and processing time. This is yak shaving for
publishing this data structure in ic_types and making it WASM (and canister)
friendly, with the hope we can move the certified asset canister to using this
(and hopefully more people).
=> refactor: move HashTree to use Cows instead of owning the values

ic-agent/src/agent/mod.rs
refactor Agent.call_and_wait so that `call` and `wait` functionality can be called separately, and added a `poll` method
=> refactor: UpdateCall, Agent.poll, Agent.wait

icx-proxy/src/main.rs
Add command-line parameter `--proxy <url>` which, if present, forwards requests with path beginning with `/_/` to the specified endpoint.
Used by `dfx` to serve data from  `/_/candid`
=> feat: --proxy: forward /_/ to a specified url

Cargo.lock, ic-agent/Cargo.toml, ic-identity-hsm/Cargo.toml, ic-types/Cargo.toml, ic-utils/Cargo.toml, icx-proxy/Cargo.toml, icx/Cargo.toml
ic-types to 0.1.3 but this is actually a breaking change.
It would be 0.2.0 but there is a circular dependency with candid -> ic-types 0.1.2 and cannot be built.
=> chore: update ic-types to 0.1.3 (should be 0.2.0) and dependencies

ic-agent/src/agent/replica_api.rs
`#[serde(skip_serializing_if = "Option::is_none")]` without `#[serde(default)]` causes deserialization to fail.
=> fix: replica_api deserialization

ic-agent/Cargo.toml, ic-identity-hsm/Cargo.toml, ic-types/Cargo.toml, ic-utils/Cargo.toml, icx-proxy/Cargo.toml, icx/Cargo.toml
icx: 0.2.1 => 0.2.2
ic-agent: 0.5.0 => 0.5.1
icx-proxy: 0.3.0 => 0.3.1
ic-identity-hsm: 0.3.1 => 0.3.2
ic-utils: 0.3.1 => 0.3.2
ic-types: 0.1.3 => 0.1.4
=> chore: release of ic-agent

ic-utils/src/canister.rs
Fixes build errors of form:
```
error[E0277]: `(dyn std::error::Error + 'static)` cannot be shared between threads safely
--> src/dfx/src/commands/canister/call.rs:278:32
|
278 |                   let canister = Canister::builder()
|  ________________________________^
279 | |                     .with_agent(agent)
280 | |                     .with_canister_id(canister_id)
281 | |                     .build()
282 | |                     .map_err(DfxError::from)?;
| |____________________________________________^ `(dyn std::error::Error + 'static)` cannot be shared between threads safely
```
Required by https://github.com/dfinity/sdk/pull/1719
=> feat: add Send and Sync so CanisterBuilderError can be shared between threads safely

ic-types/Cargo.toml
This fixes at least the following case:
1. Clone agent-rs into `~/agent-rs`
2. Create a new project `~/ic-types-test`
3. Add a dependency on `../agent-rs/ic-types`
4. `~/ic-types-test` fails to build
5. Apply the change from this PR in `~/agent-rs`
6. `~/ic-types-test` builds
Fixes https://github.com/dfinity/agent-rs/issues/208
=> fix: enable serde feature "derive" for non-dev

Cargo.lock, Cargo.toml, icx-cert/Cargo.toml, icx-cert/src/main.rs, icx-cert/src/pprint.rs
This change introduces a new command-line tool for debugging certified
HTTP responses.  The tool downloads the document with the specified
URL and pretty-prints the contents of the IC-Certificate header.
=> feat: add icx-cert tool

ic-agent/src/identity/basic.rs, ic-agent/src/identity/secp256k1.rs, ic-identity-hsm/src/hsm.rs
For some reason, these imports are needed when compiling agent-rs for dfx.  Fixes errors of this form:
```
error[E0433]: failed to resolve: use of undeclared type `BigUint`
--> /Users/ericswanson/.cargo/git/checkouts/agent-rs-6af15f3bfa206490/8fbdafa/ic-agent/src/identity/basic.rs:66:22
|
66 |     let id_ed25519 = oid!(1, 3, 101, 112);
|                      ^^^^^^^^^^^^^^^^^^^^ not found in this scope
|
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
|
1  | use simple_asn1::BigUint;
|
```
This is needed for https://github.com/dfinity/sdk/pull/1736
=> chore: re-add BigUInt, OID imports needed when building for dfx

ic-utils/src/interfaces/http_request.rs, icx-proxy/src/main.rs
Candid 0.7.1 does not support decoding a Record into an IDLValue.  We were using this in an unsupported way with Candid 0.6.x, but it doesn't work anymore.
So, this commit specifies the exact type of the streaming http response token.  Unfortunately, this means that we will no longer support arbitrary token types, but this is the best that we can do until Candid supports generic types: https://github.com/dfinity/candid/issues/245
=> fix: icx-proxy panic when decoding a response to http_request

Cargo.lock, ic-agent/Cargo.toml, ic-utils/Cargo.toml, icx-proxy/Cargo.toml, icx/Cargo.toml, ref-tests/Cargo.toml
See https://dfinity.atlassian.net/browse/SDK-57
Due to security vulnerability
```
ID:       RUSTSEC-2021-0072
Crate:    tokio
Version:  1.4.0
Date:     2021-07-07
URL:      https://rustsec.org/advisories/RUSTSEC-2021-0072
Title:    Task dropped in wrong thread when aborting `LocalSet` task
Solution:  upgrade to >= 1.5.1, < 1.6.0 OR >= 1.6.3, < 1.7.0 OR >= 1.7.2, < 1.8.0 OR >= 1.8.1
Dependency tree:
tokio 1.4.0
```
=> chore: upgrade to tokio 1.8.1

Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/lib.rs, ic-asset/Cargo.toml, icx-proxy/Cargo.toml
When there is an upgrade in `ic-types` itself, we won't need wait for `candid` upgrade first.
=> chore: ic-agent depends on ic-types

.github/workflows/icx_asset.yml, .github/workflows/provision-darwin.sh, .github/workflows/provision-linux.sh, .github/workflows/shellcheck.yml, Cargo.lock, Cargo.toml, e2e/bash/icx-asset.bash, e2e/bash/util/assertions.bash, icx-asset/Cargo.toml, icx-asset/README.md, icx-asset/src/main.rs
Adds `icx-asset` command-line tool, with a single command: `sync`, which synchronizes the (recursive) contents of a directory to an asset canister.
Also added github workflow e2e (bats) tests, and a shellcheck CI step for them.
=> feat: add icx-asset command-line tool

.github/workflows/ic-ref.yml, .github/workflows/icx_asset.yml, .github/workflows/netlify.yml, .github/workflows/shellcheck.yml, .github/workflows/test.yml
When we renamed the `master` branch to `main`, we stopped getting the little green checks in the commit history.
=> chore: update workflow scripts to refer to main branch

.github/workflows/ic-ref.yml
Copied from https://github.com/dfinity/agent-rs/pull/228
The ic-ref repo requires a github token (since it's a private repo).  By using the public ic-hs repo, we won't need that token.  That will allow us to remove the IC_REF_TOKEN secret from settings, and to then run ic-ref tests against `pull_request` (the PR branch) rather than `pull_request_target` (the main branch).
=> chore: use ic-hs rather than ic-ref; remove IC_REF_TOKEN secret

.github/workflows/ic-ref.yml
Prerequisite for merging this pr: removal of the IC_REF_TOKEN from github repo settings.
Since we're now using the public ic-hs repo, we don't need a github token in order to access it, and so we can run CI against the PR branch (`pull_request`) rather than the PR's base branch (`pull_request_target`).
=> fix: run ic ref tests against pr branch

e2e/bash/icx-asset.bash, icx-asset/src/main.rs
Sample output:
```
$ icx-asset ls ryjl3-tyaaa-aaaaa-aaaba-cai
2021-07-19 13:11:59           25397 /logo.png                                          (image/png, identity)
2021-07-19 13:11:59              24 /sample-asset.txt                                  (text/plain, identity)
2021-07-19 13:11:59             340 /index.html                                        (text/html, gzip)
2021-07-19 13:11:59             570 /index.html                                        (text/html, identity)
2021-07-19 13:11:59          148995 /index.js.map                                      (text/plain, gzip)
2021-07-19 13:11:59          649242 /index.js.map                                      (text/plain, identity)
2021-07-19 13:11:59             263 /main.css …
```
=> feat: icx-asset ls

icx/src/main.rs
Taking call arguments from command line would exceed max limit for big inputs. This adds support to read from stdin when the input is `-`.
Also fixed a minor problem to properly exit with non-zero exit code when error.
=> feat: Add an option to let icx read from stdin

ic-agent/src/agent/agent_error.rs, ic-agent/src/agent/http_transport.rs
This also changes `ReqwestHttpReplicaV2Transport` to be generic via `ReqwestHttpReplicaV2TransportImpl` in order to make the field access more useful.
It's possible to do this without introducing a new type name, but doing so would break existing code.
=> feat: expose `PasswordManager` field via methods

ic-agent/src/agent/agent_config.rs, ic-agent/src/agent/builder.rs, ic-agent/src/agent/mod.rs, ic-agent/src/agent/nonce.rs, ic-agent/src/lib.rs, ic-utils/src/call/expiry.rs
Replace `NonceFactory` with trait and generics to give more control.
Adds some renaming to keep backwards compatibility, but transient types like `QueryBuilder`, which are not expected to be explicitly named, retain their old names just with default generics, resulting technically breaking back compat (but not realisticially for any actual users).
=> feat: expose `NonceGenerator` field via methods

Cargo.lock, ic-agent/Cargo.toml, ic-asset/Cargo.toml, ic-identity-hsm/Cargo.toml, ic-utils/Cargo.toml, icx-cert/Cargo.toml, icx-proxy/Cargo.toml
Updated dependencies reported by `cargo outdated -R` that did not result in compilation errors.
These were left:
- webpki-roots: compile error due to pulling in 0.21.4 and 0.22.0
- clap: 3.0.0-beta.4 only compiles with unstable features
- cargo_metadata: compile error when trying to increment release version
=> chore: update outdated dependencies

Cargo.lock, zzz-release/Cargo.toml, zzz-release/src/main.rs
cargo_metadata 0.14.0 depends on semver 1.0.0, which no longer provides Version.increment_minor() or Version.increment_patch().
=> chore: update cargo_metadata library

.github/workflows/ic-ref.yml
Don't manually add /opt/ghc/bin to the path, since it doesn't seem to be present anymore (maybe from an invalidated cache?) and `ghc --version` reports the expected value.
Compare the build results on main for these two commits:
- https://github.com/dfinity/agent-rs/commit/f7de7670aa3870023fa45d5b5cee719b6eb7a012 ([passed](https://github.com/dfinity/agent-rs/runs/3438435945#step:9:17) Aug 26 2021)
- https://github.com/dfinity/agent-rs/commit/4dbe4d4df4d6ab3d0189bd00da16e3908c7fd698 ([failed](https://github.com/dfinity/agent-rs/runs/3655580805#step:9:11) Sep 20 2021)
The failure is
```
Run ls -l /opt/ghc/
ls: cannot access '/opt/ghc/': No such file or directory
Error: Process completed with exit code 2.
```
The previously successful output looked like this:
```
Run ls -l /opt/ghc/
total 12 …
```
=> chore: do not add /opt/ghc to path, since it is not found.

Cargo.lock, ic-agent/CHANGELOG.md, ic-agent/Cargo.toml, ic-asset/Cargo.toml, ic-identity-hsm/Cargo.toml, ic-utils/Cargo.toml, icx-asset/Cargo.toml, icx-cert/Cargo.toml, icx-proxy/Cargo.toml, icx/Cargo.toml
ic-identity-hsm: 0.3.5 => 0.3.6
ic-utils: 0.6.0 => 0.7.0
icx-asset: 0.3.0 => 0.4.0
ic-asset: 0.3.0 => 0.4.0
icx-cert: 0.4.0 => 0.5.0
ic-agent: 0.8.0 => 0.9.0
icx: 0.5.0 => 0.6.0
icx-proxy: 0.6.0 => 0.7.0
- Add `replica_health_status` to `Status`
- Add support for multiple controllers, including wallet and management canister interfaces
- Update dependencies
=> chore: release agent 0.9.0

Cargo.lock, ic-agent/Cargo.toml, ic-identity-hsm/Cargo.toml
This PR upgrades to simple_asn 0.6.0 in order to remove a dependency on `chrono`.
This is because of a cargo audit failure with no safe upgrade available:
https://rustsec.org/advisories/RUSTSEC-2020-0159
icx-asset, icx-cert, and zzz-release still depend on chrono.
=> chore: remove chrono dependency from ic-agent, ic-identity-hsm

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/http_transport.rs, ic-asset/Cargo.toml, ic-identity-hsm/Cargo.toml, ic-utils/Cargo.toml, icx-asset/Cargo.toml, icx/Cargo.toml
Update crate dependencies reported by `cargo outdated -R`, with the exception of clap, which remains pinned at **3.0.0-beta.2**
This fixes an issue seen by users of the crate that updated to reqwest 0.11.7, where connections would fail with the following error:
```
Could not create HTTP client.: reqwest::Error { kind: Builder, source: "Unknown TLS backend passed to `use_preconfigured_tls`" }
```
This also fixes https://dfinity.atlassian.net/browse/SDK-115 by removing the direct dependency on webpki-roots altogether.
=> chore: update cargo dependencies

.github/workflows/provision-darwin.sh
macos-latest is being rolled out, scheduled to be completed Dec 13.  https://github.com/actions/virtual-environments/issues/4060
This change will handle macos-latest being either macos-10.15 or macos-11.
=> chore: fix darwin provisioning due to macos-latest upgrade

CHANGELOG.md, ic-asset/src/asset_canister/batch.rs, ic-asset/src/asset_canister/chunk.rs, ic-asset/src/lib.rs, ic-asset/src/plumbing.rs, ic-asset/src/retryable.rs, ic-asset/src/semaphores.rs, icx-asset/src/commands/sync.rs, icx-asset/src/main.rs
There are a few things going on here.
The main fix here is in `create_chunk`: using a `count_timeout` rather than a `timeout`.  This is because a semaphore is acquired after starting the waiter but before each attempt to send the update request.  The result was that all retries would fail after the first 30 seconds, because the timeout for every chunk was started at the same time.
Other changes:
- Use exponential backoff for the retry delay.
- Call Waiter.async_wait rather than Waiter.wait, since we are in an async fn, in order to not prevent the runtime from swapping the current task.
- Check for failure due to being out of cycles, or 403/unauthorized in general, and don't retry.
- Added a new `create_chunk` semaphore, which limits how many chunks can be in the process of being …
=> fix: retry failures when uploading assets

ic-utils/src/interfaces/http_request.rs
This lays the groundwork for upgrading HTTP requests from query calls to update calls.
It applies the changes from https://github.com/dfinity/agent-rs/pull/195 that are specific to `ic-utils` so that they can be used downstream in `icx-proxy`.
=> feat: Provide support for upgrading HTTP requests

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-asset/Cargo.toml, ic-identity-hsm/Cargo.toml, ic-utils/Cargo.toml, icx-asset/Cargo.toml, icx-cert/Cargo.toml, icx/Cargo.toml
- Add support for upgrading HTTP requests, which is needed for https://github.com/dfinity/icx-proxy/pull/6
- Also updated all dependencies reported by `cargo outdated -R`
=> chore: release rust agent 0.10.2

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-asset/Cargo.toml, ic-identity-hsm/Cargo.toml, ic-utils/Cargo.toml, icx-asset/Cargo.toml, icx-cert/Cargo.toml, icx/Cargo.toml, ref-tests/Cargo.toml
Updated candid and ic-types, along with minor updates to other dependencies.
=> chore: release rust agent 0.11.0

.github/workflows/provision-darwin.sh, .github/workflows/test.yml
Fixes errors seen on macos-11 runners of the form:
```
= note: ld: warning: directory not found for option '-L/usr/local/opt/openssl@3/lib'
ld: library not found for -lssl
```
=> fix: openssl build error on macos-11

ic-agent/src/agent/mod.rs, ic-agent/src/lib.rs
To allow more flexible ways to query canister info on the client side
=> chore: make read_state_raw public

CHANGELOG.md, ic-utils/src/interfaces/http_request.rs
This will be a breaking (minor version increment) release.
=> fix: change HttpResponse.upgrade to Option<bool> for backwards compatibility

ic-asset/src/asset_canister/protocol.rs, ic-asset/src/retryable.rs
The struct BatchOperationKind which is used to send batch commands to the certified asset canister
using icx-asset is encoded into Candid which uses hashes of enum variants as keys.  This enum
has a "Clear" field in the certified asset canister, but a _Clear field in the ic-asset crate because
it was not used and was giving a warning.  However, because of the Candid format dependency
on the names of the variants these are incompatible which causes "icx-asset ... sync" to fail.
This PR changes the name to the compatible "Clear" and avoids the warning with #[allow(dead_code)].
A better change would be to add these types to an ic-certified-assets-types crate or somesuch,
but I will leave that to the reviewers to decided.
Signed-off-by: John Plevyak <jplevyak@gmail.com>
=> fix: candid compatibility: mismatched enum.

.github/workflows/icx_asset.yml, .github/workflows/provision-darwin.sh, .github/workflows/provision-linux.sh
Also DRY the workflow definition.
It's expected that the `icx-asset-darwin` and `icx-asset-linux` required statuses do not pass, because this PR changes these and aggregates them into a single required status.  Once this PR is approved, I will update the required statuses and then merge.
=> chore: Run e2e tests against dfx 0.7.2 and 0.8.4

ic-utils/src/interfaces/http_request.rs
Test if we can decode without the `update` field.
=> test: regression test for `HttpResponse` decode

CHANGELOG.md, ic-agent/src/identity/secp256k1.rs
Jira: [SDK-317](https://dfinity.atlassian.net/browse/SDK-317)
Secp256k1Identity failed to check if a key actually is a secp256k1 key. It now checks for the correct curve params.
=> chore: valiate curve params when loading identity

ic-agent/src/agent/mod.rs, ref-tests/tests/ic-ref.rs
Jira: [SDK-133](https://dfinity.atlassian.net/browse/SDK-133)
When a non-default root key is found, it has already been fetched. No need to ask the network a second time.
=> chore: fetch_root_key fetches only the first time

.github/workflows/ic-ref.yml, ic-identity-hsm/src/lib.rs, ref-tests/tests/ic-ref.rs
The ic-hs version used in the ic-ref integration test does not build without using cached artefacts, which is not replicable locally. With this update, it's possible to run ref-tests locally again.
Per [EXC-738](https://dfinity.atlassian.net/browse/EXC-783) there is no upper limit for cycles balances anymore, so the corresponding test has been adjusted.
=> chore: update ic-hs to a version that builds from source

ic-utils/src/interfaces/http_request.rs
With a little elbow grease we can even get around `Func`'s limitations.
Introduces a new type `HttpRequestStreamingCallback` which properly serializes/deserializes callbacks of the form:
`callback : (Token) -> (StreamingCallbackHttpResponse) query;`
We use `ArgToken` (which returns `Type::Empty`  from `ty`) for the abstract form, because arguments subtype in the opposite direction so:
`callback : (Empty) -> (StreamingCallbackHttpResponse<Reserved>) query;`
Will match without knowing what the `Token` contents are.
=> fix: workaround for dfinity/candid#273

icx/src/main.rs
Think this `exit(1)` didn't achieve what it was supposed to do (#229), it is better to remove it.
=> fix: Remove the erroneous exit

ic-utils/src/interfaces/wallet.rs, ref-tests/tests/ic-ref.rs, ref-tests/tests/integration.rs
The default functions are changed to use the 128-bit canister functions, and the old canister functions are accessible under explicitly 64-bit functions (e.g. `.wallet_send` &rarr; `:wallet_send128`, `.wallet_send64` &rarr; `:wallet_send`).
=> feat: Update wallet interface for 128-bit API

ic-utils/src/canister.rs, ic-utils/src/interfaces.rs, ic-utils/src/interfaces/http_request.rs, ic-utils/src/interfaces/management_canister.rs, ic-utils/src/interfaces/management_canister/builders.rs, ic-utils/src/interfaces/wallet.rs, ref-tests/tests/ic-ref.rs, ref-tests/tests/integration.rs
The existing system of `Canister<Interface>` has several problems:
- The documentation is in an unfindable location
- You can't make intra-rustdoc links to the methods
- Crates other than ic-utils are unable to `impl` directly for Canister in this way
- All the generic types involved cart around an extra type parameter just to hold the canister container
This inverts the relationship to `InterfaceCanister(Canister)`, with a Deref impl to preserve existing convenience, solving all the above problems.
=> feat: Remove parameterized canister pattern

Cargo.lock, ic-utils/Cargo.toml, ic-utils/src/interfaces/wallet.rs, ref-tests/tests/ic-ref.rs, ref-tests/tests/integration.rs
Per discussion elsewhere, using 128-bit by default causes other problems, and #330 opens us up to storing the version. So this makes 128-bit functions as specific as the 64-bit ones, and the non-annotated functions instead select the correct version based on the version string, which it fetches when the interface object is initialized.
=> feat: revamp 128-bit wallet interface

ic-utils/src/canister.rs, ic-utils/src/interfaces/wallet.rs, ref-tests/tests/ic-ref.rs, ref-tests/tests/integration.rs
This makes a few consistency improvements towards wallet_call and friends.
- Argument is now constructible from values in a one-liner if you don't need builder syntax but are calling a function that requires one
- `WalletCanister::call`/`call64`/`call128` now take `Principal` instead of `Canister`. Every element of the canister's configuration was ignored except the principal, so this avoids misleading callers as well as not requiring constructing do-nothing canisters for cases like `Principal::management_canister`.
- `call_forward` is removed. Same story - all configuration is ignored, so wrapping the high-level abstraction makes no sense if it's not used. It also was not usable with interface functions in the first place, which is so centrally the use-case that I thought it couldn't be …
=> feat: Improve wallet call forwarding API

ic-utils/src/interfaces/wallet.rs, ref-tests/tests/integration.rs
This should be the last major thorn in the wallet interface object.
=> feat: wallet_send takes Principal instead of &Canister

CHANGELOG.md, ic-agent/src/agent/http_transport.rs
Adds `ReqwestHttpReplicaV2Transport::create_with_client`.
Also re-exports `reqwest` for ease of version matching.
This makes it much easier to do custom connection stuff (e.g. self-signed certs for farm IC testing).
Local testing with custom icx-proxy.
=> feat: `ReqwestHttpReplicaV2Transport::create_with_client`

CHANGELOG.md, ic-agent/Cargo.toml
If consumers of ic-agent didn't update their reqwest dependency manually, agent construction would fail with this error:
```
Could not create HTTP client.: reqwest::Error { kind: Builder, 
source: "Unknown TLS backend passed to use_preconfigured_tls" } 
```
Update the dependency requirement to be at least reqwest >= 0.11.7.
=> fix: raise minimum reqwest version to avoid TLS backend error

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/identity/secp256k1.rs
Update dependencies so that `cargo outdated -R` again reports clean.  This even simplified some of the DER-encoding.
Covered by existing unit tests.
=> chore: update dependencies

ic-agent/Cargo.toml, ic-asset/Cargo.toml, ic-identity-hsm/Cargo.toml, ic-utils/Cargo.toml, icx-asset/Cargo.toml, icx-cert/Cargo.toml, icx/Cargo.toml
So that crates.io links to the repo
=> fix: add repository links to cargo manifest

CHANGELOG.md, e2e/bash/icx-asset.bash, ic-asset/src/sync.rs, icx-asset/README.md, icx-asset/src/commands/sync.rs, icx-asset/src/main.rs
This is a breaking change.
fix: ic-asset::sync() accepts multiple source directories
It also now skips filenames and directories that begin with "." (as dfx does),
and reports an error if more than one asset resolves to the same key.
This is to account for asset source directories that may in the future contain
a configuration file .ic-asset.json.  More than one source directory may contain
such a file, but its configuration should only apply to the assets in the
corresponding directory.
Added e2e tests
=> fix: ic-asset::sync() accepts multiple source directories

CHANGELOG.md, Cargo.lock, e2e/bash/icx-asset.bash, ic-asset/Cargo.toml, ic-asset/src/asset_canister/protocol.rs, ic-asset/src/asset_config.rs, ic-asset/src/http_headers_config.rs, ic-asset/src/lib.rs, ic-asset/src/operations.rs, ic-asset/src/plumbing.rs, ic-asset/src/sync.rs, ic-asset/src/upload.rs
- detects if `.ic-assets.json` config file is present when syncing assets, then uses glob values from that file to match against the assets in the directory which is being synced
Implements [SDK-479](https://dfinity.atlassian.net/browse/SDK-479)
- unit tests in http_headers_config.rs
- plugged this into dfx and it doesn't jam 
- what type should be used for HashMap's value of `pub(crate) type HeadersConfig = HashMap<String, Value>;` (maybe consider this https://docs.rs/http-serde/1.1.0/http_serde/index.html instead of `serde_json::Value`)
=> feat: support for asset canister config files in `ic-assets`

CHANGELOG.md, ic-asset/src/asset_canister/protocol.rs, ic-asset/src/asset_config.rs, ic-asset/src/operations.rs
Adds support for `headers` field in `.ic-assets.json` file
Implements https://dfinity.atlassian.net/browse/SDK-473
Already been tested
=> feat: support for custom HTTP headers asset canister configuration in ic-assets 

Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/signed.rs, ic-asset/Cargo.toml, ic-utils/Cargo.toml, icx-asset/Cargo.toml, icx/Cargo.toml, ref-tests/Cargo.toml
ic-types 0.4.0 contains an important performance fix.
=> chore: Upgrade to candid 0.7.15 and ic-types 0.4.0

CHANGELOG.md, ic-asset/src/asset_config.rs, ic-asset/src/sync.rs
Currently, custom configured HTTP headers coming from `.ic-assets.json` have the value-part of the header surrounded with double-quotes, e.g.
```
Access-Control-Allow-Methods: "GET"
```
which is not desirable, since:
1. there is no way for an end developer to disable this
1.  most header values don't need to be wrapped with quotes ([example](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods))
This PR fixes that, so the header will end up looking like this:
```
Access-Control-Allow-Methods: GET
```
Passing unit tests.
=> fix: strip quotes from custom-configured HTTP headers

.github/workflows/e2e.yml
e2e tests often get stuck or take forever and fail on timeout for dfx == `0.7.2`. Since the version is quite old, we're dropping it from our CI.
=> chore(tests): remove dfx `0.7.2` from test matrix

ic-agent/src/agent/builder.rs, ic-agent/src/agent/http_transport.rs, ic-agent/src/agent/mod.rs, ic-agent/src/agent/replica_api.rs, ic-agent/src/agent/status.rs, ic-agent/src/request_id/mod.rs
These are all no-impact changes. Nothing seems worthy of `CHANGELOG` since there are no changes to the public interface or functionality.
* Cleanup imports
* fix doc comments
* Introduce private `AgentFuture` alias to improve readability
* Switch to `async` blocks instead of private `run` helpers
`cargo test && cargo clippy && cargo doc`
=> chore: cleanup ic-agent

CHANGELOG.md, ic-agent/src/agent/mod.rs
This change adds the `Agent::set_identity` method modifying the
identity after constructing the agent.
Motivation: I am writing a test suite where I must send messages to
the same canister from different identities. Being able to
Agent::clone() followed by Agent::set_identity() would significantly
simplify (and speed up) my code.
=> feat: allow setting agent identity after construction

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/mod.rs, ic-agent/src/agent/response_authentication.rs, ic-agent/src/lib.rs
The `miracl_core_bls12381` crate was created for use in the IC however it has a number of performance and security issues which have caused us to remove all uses of it within the IC itself. Speaking on behalf of the DFINITY crypto team which up until now has maintained this crate, we would at this point much rather yank all versions and forget it ever existed.
This replaces the code that used `miracl_core_bls12381` with instead using a small crate that uses the `zkcrypto/bls12_381` library.
Just with `cargo test`. Not sure if there is anything else that is required/useful if so let me know.
=> fix: Remove use of the miracl_core_bls12381 crate

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/response_authentication.rs
This PR fixes the method `lookup_request_status` to handle proofs of absence introduced in this [MR](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/7661).
The case
```
LookupResult::Unknown => Err(LookupPathUnknown(path_status.into())),
```
will be updated in the function `lookup_request_status` after this [MR](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/7661) is merged.
=> fix: lookup request status

CHANGELOG.md, ic-utils/src/interfaces/management_canister/builders.rs
This PR enables incremental changes in IC tests specifying an effective canister id when creating canisters. After all these changes are implemented, the special case of `provisional_create_canister_with_cycles` in checking certificate delegation can be removed.
=> feat: specifying effective canister id for canister creation

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/http_transport/hyper_transport.rs, ic-agent/src/agent/http_transport/reqwest_transport.rs, ic-agent/src/agent/mod.rs, ic-agent/src/agent/response_authentication.rs, ic-agent/src/export.rs, ic-agent/src/hash_tree/mod.rs, ic-agent/src/hash_tree/tests.rs, ic-agent/src/lib.rs, ic-identity-hsm/Cargo.toml, ic-identity-hsm/src/hsm.rs, ic-utils/Cargo.toml, ic-utils/src/canister.rs, icx-cert/Cargo.toml, icx-cert/src/pprint.rs, icx/Cargo.toml, ref-tests/Cargo.toml
No more depend on `ic-types` which will be retired after this change.
CI
=> feat: update candid v0.8.0, move hash_tree from ic-types

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/agent_error.rs, ic-agent/src/agent/mod.rs, ic-agent/src/lib.rs, ic-utils/Cargo.toml, ic-utils/src/call.rs, ic-utils/src/canister.rs, ic-utils/src/interfaces/management_canister/builders.rs, ic-utils/src/interfaces/wallet.rs, icx/Cargo.toml, icx/src/main.rs, ref-tests/Cargo.toml, ref-tests/src/utils.rs, ref-tests/tests/ic-ref.rs, ref-tests/tests/integration.rs
Implements SDK-824.
This additionally removes garcon from the public API; the backoff numbers dfx uses are good enough for anyone, and users who want a shorter timeout can use tokio's timeout function.
=> feat: Replace garcon with backoff

CHANGELOG.md, ic-certification/src/hash_tree/mod.rs, ic-certification/src/hash_tree/tests.rs
Adds a `subtree_lookup` method to `HashTree` and `HashTreeNode`. This method will return a subtree if it can be found at the provided path.
Relates to [#TT-42](https://dfinity.atlassian.net/browse/TT-42)
Unit tests have been provided.
=> feat(ic-certification): add subtree_lookup method

ic-certification/src/hash_tree/mod.rs, ic-certification/src/hash_tree/tests.rs, ic-certification/src/lib.rs
Returning a hash tree allows for easier lookups on the returned hash tree. If a hash tree node is returned then this is more difficult as the methods are all private. 
Relates to [#TT-42](https://dfinity.atlassian.net/browse/TT-42)
Note, I didn't update the changelog since this feature is still unreleased and I don't think this commit affects the changelog message, I'm happy to update it though if you disagree.
Unit tests have been updated.
=> fix(ic-certification): update subtree_lookup method to return hash tree instead of a hash tree node

CHANGELOG.md, ic-certification/src/certificate.rs
This makes working with the `Certificate` and `Delegation` structs much easier 
N/A
=> feat: derive Clone on `Certificate` and `Delegation` structs

.github/workflows/ic-ref.yml, CHANGELOG.md, ic-utils/src/interfaces/http_request.rs
BREAKING CHANGE: Adds an new property to the HttpRequest interface to allow for specifying the desired certificate version for the canister to return.
Relates to [#TT-35](https://dfinity.atlassian.net/browse/TT-35)
I didn't add unit tests because there was no previous unit tests, so I assume it was an active decision to not maintain unit tests for this particular piece, but I'm happy to add some if wanted.
I've already used this in the e2e tests for the response verification repo and it's working well there: https://github.com/dfinity/response-verification/blob/nathan/update-e2e-tests/packages/ic-response-verification-tests/src/main.rs#L95-L98
=> feat: add certificate version to http request canister interface

CHANGELOG.md, Cargo.lock, Cargo.toml, ic-agent/Cargo.toml, ic-certification/Cargo.toml, ic-identity-hsm/Cargo.toml, ic-utils/Cargo.toml, icx-cert/Cargo.toml, icx/Cargo.toml, ref-tests/Cargo.toml
Utilize the new cargo feature to inherit value from workspace config.
From now on, we will only need modify the version in the root Cargo.toml.
=> chore: release v0.23.1

ic-agent/src/lib.rs
Reported by @mariodfinity
Manually checked that `cargo doc -p ic-agent` produces the right link.
=> fix: broken link to Agent

CHANGELOG.md, ic-agent/src/agent/mod.rs
Enable clients to get the currently used root key through the `read_root_key` method.
N/A
=> feat: enable clients to get the currently used root key

.github/workflows/conventional-commits.yml, CHANGELOG.md
I copied the jobs from the [conventional commits configuration file from the SDK Repo.](https://sourcegraph.com/github.com/dfinity/sdk/-/blob/.github/workflows/conventional-commits.yml?L20-41)
This allows us to have PRs with a suffix of `!`, and should fix the job failing for the title of #422.
Fixes #423
N\A. The job is the same as used in https://sourcegraph.com/github.com/dfinity/sdk/-/blob/.github/workflows/conventional-commits.yml
=> fix: Fixed bug in conventional commits file

.github/workflows/conventional-commits.yml, CHANGELOG.md
The conventional commits workflow no longer needs to run on `pull_request_target`, since the repo now holds all of the code.
Also note: Github workflows that run against `pull_request_target` won't be tested in a PR that changes that workflow. 
This is the same workflow as https://github.com/dfinity/sdk/blob/master/.github/workflows/conventional-commits.yml
=> ci: run conventional commits workflow from pull request

CHANGELOG.md, icx-cert/src/pprint.rs
This fixes an error where the canister would not respond with an `ic-certificate` header if the `User-Agent` header was not included in the request, thus breaking the application
Fixes #418 
```bash
$ cd icx-cert
$ cargo run print "https://mzgdj-vqaaa-aaaag-qanaa-cai.ic0.app"
```
Now responds with the pretty printed tree instead of:
`Error: IC-Certificate header not found:`
=> fix: update `icx-cert` reqwest call to include a user agent

CHANGELOG.md, ic-utils/src/interfaces/http_request.rs
This puts the HTTP request interface in line with recent changes to the spec: https://github.com/dfinity/interface-spec/pull/147
The `certificate_version` should always be ignored on Update calls since its not relevant. Requiring it to be provided confuses this.
I have not added any new tests for this.
=> fix: do not send certificate_version on http update requests

CHANGELOG.md, ic-utils/src/interfaces/http_request.rs
Using `u128` instead of `u16` broke the request sent to the asset canister, so even if `certificate_version` was set to `2` the asset canister was always responding with version 1.
This was found by updating the e2e tests on the response verification side to assert that the correct version of response verification is used. The assertion failed for v2 tests because the version was always 1. With this change all tests are passing.
=> fix: http_request not matching expected candid

.gitattributes, CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/agent_error.rs, ic-agent/src/agent/http_transport/reqwest_transport.rs, ic-agent/src/identity/basic.rs, ic-agent/src/identity/secp256k1.rs, ic-agent/src/lib.rs
The spec doesn't support any type of HTTP authentication so there is no point in the extra functionality provided the by Password manager.
In addition the MR:
- updates version so of some cargo dependencies.
- removes unused errors (the error space is already too big to be meaningfully handled programatically)
CI
BREAKING CHANGE: The MR removes some of the publicly visible methods.
=> feat: remove the PasswordManager

.gitattributes, CHANGELOG.md, Cargo.lock, Cargo.toml, ic-agent/Cargo.toml, ic-agent/src/agent/agent_config.rs, ic-agent/src/agent/agent_error.rs, ic-agent/src/agent/builder.rs, ic-agent/src/agent/mod.rs, ic-agent/src/agent/replica_api.rs, ic-agent/src/export.rs, ic-agent/src/lib.rs, ic-utils/Cargo.toml, icx/Cargo.toml, ref-tests/Cargo.toml
We want to use the public agent-rs as much as possible in the core protocol code and remove the existing custom solutions we have. For this purpose we may need to bridge some differences. For example there is no point in polling for a response more than 5 minutes since the replica will GC any ingress messages within 5 min anyway.
The MR also updates versions of some dependencies as well.
CI
=> fix: multiple fixes to the agent-rs, most notably having 5 min limit on the retry loop while polling 

.github/workflows/lint.yml, .github/workflows/test.yml, CHANGELOG.md, ic-agent/Cargo.toml, ic-agent/src/agent/agent_test.rs, ic-agent/src/agent/http_transport/reqwest_transport.rs, ic-agent/src/agent/mod.rs
It is necessary to put the `wasm-bindgen` build target behind a feature in order to use it in the [ic repo](https://github.com/dfinity/ic). Due to bazel and cargo's feature unification, some transitive dependencies such as `getrandom`, `backoff`, and `time` crates were unified which were breaking our builds in the main IC-repo, making it impossible to use the current state of `ic-agent`.
As a consequence, we also have to update the GitHub workflows to include `--features wasm-bindgen`.
`cargo test`.
=> fix: put wasm-bindgen build target behind a feature.

Cargo.lock, Cargo.toml, ic-agent/Cargo.toml, icx-cert/Cargo.toml, icx-cert/src/pprint.rs
Replaces `chrono` with `time` in `icx-cert`. Resolves our favorite Dependabot alert.
=> chore: Replace `chrono` with `time`

Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/http_transport/reqwest_transport.rs
We use a function `use_preconfigured_tls`, which requires ic-agent to be using the same version of rustls that reqwest is. However reqwest has a habit of bumping it in minor releases, making this impossible to track in reality. This PR removes the TLS configuration code, which was only ever reproducing the defaults anyway. Fixes #284.
=> fix: stop using preconfigured tls

Cargo.lock, Cargo.toml, icx-cert/Cargo.toml
Includes #441, which fixes an issue in 0.24.0 that caused guaranteed runtime errors when using the agent in a way invisible to our CI.
=> chore: Release 0.24.1

ic-agent/src/agent/http_transport/mod.rs
This continues the deprecation path of the transport reexports by marking them deprecated rather than just hidden. To be removed entirely next release.
=> chore: Update deprecations

.github/workflows/ic-ref.yml, CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/agent_test.rs, ic-agent/src/agent/mod.rs, ic-agent/src/agent/replica_api.rs, ic-agent/src/identity/anonymous.rs, ic-agent/src/identity/basic.rs, ic-agent/src/identity/mod.rs, ic-agent/src/identity/secp256k1.rs, ic-agent/src/lib.rs, ic-agent/src/request_id/mod.rs, ic-identity-hsm/Cargo.toml, ic-identity-hsm/src/hsm.rs, ic-utils/Cargo.toml, ic-utils/src/call.rs, ic-utils/src/call/expiry.rs, ic-utils/src/canister.rs, icx-cert/Cargo.toml, icx/Cargo.toml, icx/src/main.rs, ref-tests/src/utils.rs, ref-tests/tests/ic-ref.rs, ref-tests/tests/integration.rs
To support `Identity` implementations such as the Ledger Nano, the `Identity::sign` function must be able to receive the full message being signed, not just the calculated request ID. This PR exposes the envelope content map in the API and makes it the new parameter for `Identity::sign`, while refactoring several places that the content map ends up in the implementation to accommodate. 
This is a breaking change in a couple high profile places, so I took the opportunity to make a couple more related ones around unnecessarily cloning data that we've held off on making for user convenience.
=> feat!: Update Identity API to receive the full content map

Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/mod.rs, ic-utils/Cargo.toml, ic-utils/src/call/expiry.rs
`std::time::SystemTime` is incompatible with wasm-bindgen, while `time::OffsetDateTime` is not. This changes the expiry timestamp to be based on `OffsetDateTime` instead of `SystemTime`, leaving source compatibility via the From impl.
=> feat: Use `OffsetDateTime` instead of `SystemTime`

ic-utils/Cargo.toml, ic-utils/src/call.rs, ic-utils/src/interfaces/management_canister/builders.rs, ic-utils/src/interfaces/wallet.rs, rust-toolchain.toml
This allows avoiding the 0.9.x deprecation warnings from candid, at the expense of the cleanliness of `async fn`.
=> feat: Disable arc_type requirement in candid for ic-utils

.gitattributes, .github/workflows/e2e.yml, .github/workflows/fmt.yml, .github/workflows/ic-ref.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, Cargo.toml, ic-agent/src/identity/basic.rs, ic-utils/src/call/expiry.rs, rust-toolchain.toml
ProdSec recommends bumping the Rust version to 1.71.1
CI
=> chore: update Rust version

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml
Update dependencies, and switch from rustls to rustls-webpki so that `cargo audit` passes.
Fix for https://rustsec.org/advisories/RUSTSEC-2023-0052
Covered by CI
=> chore: update dependencies and switch from rustls to rustls-webpki

.github/workflows/lint.yml, Cargo.toml, ic-utils/Cargo.toml, icx/Cargo.toml
The lint action is set as `-Dclippy::all`. This errors on any Clippy lint, but not on rustc lints. The correct flag to forbid all warning lints is `-Dwarnings`.
=> chore: Fix clippy in CI

CHANGELOG.md, ic-agent/src/agent/agent_error.rs, ic-agent/src/agent/mod.rs
* Add `From` trait to coerce `candid::Error` into `ic_agent::AgentError`.
* Add `Agent::set_arc_identity` method to switch identity.
=> chore: QoL improvements

CHANGELOG.md, ic-agent/src/identity/anonymous.rs, ic-agent/src/identity/basic.rs, ic-agent/src/identity/mod.rs, ic-agent/src/identity/secp256k1.rs, ic-identity-hsm/src/hsm.rs
The two things an identity is expected to sign in the IC spec are content maps and delegations; this PR adds delegations where ic-agent currently only supports the content map.
This PR also partially reverts the constriction imposed in #443 to re-allow arbitrary garbage to be signed without being a valid content map; it, like delegations, is an explicitly *optional* feature of the Identity trait which not all implementations support.
Finally a `public_key` function is added so `sign_arbitrary(&[])` is not required in order to get the unhashed public key for the identity.
=> feat: sign delegations and arbitrary data

.github/workflows/provision-linux.sh, CHANGELOG.md, ic-utils/src/call.rs, ic-utils/src/canister.rs, ic-utils/src/interfaces/management_canister/builders.rs, ic-utils/src/interfaces/wallet.rs
* Remove argument builder from `ic-utils` to prevent requiring `Send` for `candid::Type`. It's never correct to use `IDLBuilder` in the argument builder, as Candid uses `thread_local` to resolve `TypeId`, which is not `Send`.
* Reverts #454 
=> fix: remove argument builder from ic-utils

CHANGELOG.md, Cargo.lock, Cargo.toml
Includes the latest candid changes to eliminate arc_type.
=> chore: Release version 0.27.0

CHANGELOG.md, ic-agent/src/agent/response_authentication.rs
Absence proofs have been recently enabled on the IC (see [MR](https://github.com/dfinity/ic/commit/2ac0fe91cd737977bf039c55502a31b363884c69)) and thus the IC is going to produce certificate whose lookup returns `Absent` for paths whose values are missing in the state tree. This PR reflects this change in the agent.
=> feat: Unknown lookup status of a path in certificate yields AgentError

CHANGELOG.md, ic-utils/src/canister.rs, ic-utils/src/interfaces/http_request.rs, ic-utils/src/interfaces/management_canister.rs, ic-utils/src/interfaces/management_canister/builders.rs, ic-utils/src/interfaces/wallet.rs, ref-tests/tests/integration.rs
There's no reason for the Canister methods `.update_()`, `.query_()`, `.canister_id_()`, and `.clone_with_()` to have trailing underscores.  The trailing underscores make me wonder if they're finished or not.  Added versions without.
Didn't deprecate the methods with underscores, though I'm not against doing so.
Covered by CI
=> refactor: add Canister methods with no trailing underscore

.github/workflows/ic-ref.yml, ref-tests/tests/ic-ref.rs, ref-tests/tests/integration.rs
Update the CI workflows that used ic-ref to instead run the replica.  Updated tests to account for differences seen when running against the replica rather than ic-ref.
This will allow us to add new tests for new replica functionality.
Updated the tests
=> test: run e2e/integration tests vs replica rather than ic-ref

.github/workflows/e2e.yml, .github/workflows/fmt.yml, .github/workflows/ic-ref.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, Cargo.lock, Cargo.toml, Cross.toml, icx-cert/Cargo.toml, rust-toolchain.toml
This PR raises the MSRV to 1.70 following several dependencies doing the same. Particular to 1.70 is the support for the sparse Cargo registry, to accelerate this update in particular. It also removes the distinction between the CI version and the local dev version, letting CI pick the version up from rust-toolchain.toml.
=> chore: Raise MSRV to 1.70.0

CHANGELOG.md, ic-transport-types/src/lib.rs, ic-transport-types/src/request_id.rs, ic-transport-types/src/request_id/error.rs, ic-transport-types/src/signed.rs, ref-tests/Cargo.toml, ref-tests/tests/ic-ref.rs
This PR allows request IDs to include nested maps, which necessitated a rewrite of the underlying algorithm. Required for replica-signed queries.
=> feat: Rewrite request ID calculator

Cargo.lock, ic-agent/src/agent/builder.rs, ic-agent/src/agent/mod.rs
If the agent's configured ingress expiry duration is >1m, this rounds the ingress expiry *timestamp* to the closest minute (and otherwise, rounds down to the second). This will hopefully reduce cache misses, since a nanosecond difference in the ingress expiry timestamp means a different request ID and is thus uncacheable.
Implements SDK-1259.
=> feat: Round `ingress_expiry` to the minute

CHANGELOG.md, ic-agent/src/agent/agent_test.rs, ic-agent/src/agent/status.rs, ref-tests/tests/ic-ref.rs
This PR removes non-optional `ic_api_version` field (whose value is not meaningfully populated by the replica) and optional `impl_source` and `impl_revision` fields (that are not populated by the replica) from the expected `/api/v2/status` endpoint response.
Here's the corresponding specification [MR](https://github.com/dfinity/interface-spec/pull/234).
=> feat: remove fields in expected status endpoint response

CHANGELOG.md, ic-transport-types/src/lib.rs, ref-tests/tests/integration.rs
The senders field in user delegations is not (going to be) supported in the replica implementation and thus this PR removes this field from the agent implementation.
Specification PR: https://github.com/dfinity/interface-spec/pull/246
=> feat: drop senders field from user delegations

CHANGELOG.md, ic-agent/src/agent/agent_error.rs, ic-agent/src/agent/http_transport/hyper_transport.rs, ic-agent/src/agent/http_transport/mod.rs, ic-agent/src/agent/http_transport/reqwest_transport.rs, ic-agent/src/agent/http_transport/route_provider.rs
_API Boundary Node (BN) Discovery Library_  (which is in a very recent [development](https://gitlab.com/dfinity-lab/public/ic/-/tree/master/rs/boundary_node/discower_bowndary?ref_type=heads)) is the prerequisite for the [IC-720: BN Decentralization Feature](https://forum.dfinity.org/t/boundary-node-roadmap/15562). This library will have two main responsibilities:
1. **Discovery of the API Boundary Nodes (domains)**.  Users (clients) of the IC need to know, which domains to use when "talking" to the IC. Currently, there is only one domain `ic0.app` owned by _Dfinity_. However, once BNs are decentralized, each BN will have it's own/unique domain. Moreover, BNs and their domain records could be added (or removed) from the IC registry via nns proposals. Thus, clients would need an api to …
=> feat: extend agent with a route provider feature

CHANGELOG.md, Cargo.lock, Cargo.toml, ic-agent/src/agent/http_transport/hyper_transport.rs, ic-agent/src/agent/http_transport/mod.rs, ic-agent/src/agent/http_transport/reqwest_transport.rs
This includes deprecations of previous doc(hidden) symbols, and deletions of previous deprecated symbols.
=> chore: Update to 0.30.0

CHANGELOG.md, ic-agent/src/agent/http_transport/hyper_transport.rs
Hyper transport produced a url with a double slash, namely: `/api/v2//canister/5v3p4-iyaaa-aaaaa-qaaaa-cai/query`
It seems hyper transport is not tested e2e.
=> fix: hyper-transport url

ic-agent/src/agent/mod.rs
Currently it is an error if there is a subnet in the cache and a node's signature is from a node not in the cache. This causes an error in the five minutes after a node is added to a subnet. This PR refreshes the cache once before raising the error.
=> fix: handle case where a node is added

CHANGELOG.md, Cargo.lock, Cargo.toml, ic-agent/src/agent/agent_test.rs, ic-utils/Cargo.toml, ic-utils/src/interfaces/http_request.rs, icx/Cargo.toml, icx/src/main.rs
Bump Candid to 0.10. Downstream libraries need to bump Candid to 0.10 as well.
=> chore!: bump candid

CHANGELOG.md, ic-utils/src/interfaces/management_canister.rs
This PR adds the `idle_cycles_burned_per_day` field to `StatusCallResult` of the management canister's `canister_status` method. This field is useful to compute the number of cycles the canisters burns during its `freezing_threshold`.
=> feat: add idle_cycles_burned_per_day field to StatusCallResult

Cargo.lock, Cargo.toml
I need to bump `ic-certification` to remove some git commit hash references.
🙃
=> chore: bump ic-certification

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/identity/error.rs, ic-agent/src/identity/mod.rs, ic-agent/src/identity/prime256v1.rs, ref-tests/src/utils.rs, ref-tests/tests/ic-ref.rs
The IC supports ed25519, secp256k1, and prime256v1 curves. agent-rs has the first two, but the only way to use the latter is ic-identity-hsm. This PR adds an in-memory prime256v1 `Identity` impl to complement the other two.
=> feat: Add Prime256v1Identity

Cargo.lock, ic-agent/src/agent/mod.rs, ref-tests/Cargo.toml, ref-tests/tests/integration.rs
This MR proposes the following changes:
Currently, the agent can only be used with a private key that is known to the agent. If someone wants to sign their request outside of the agent, they cannot forward this signed request using the agent. 
The agent already offers a method that lets a user forward a signed `Envelope` of `EnvelopeContent::Call` to the IC. This MR adds the same functionality for a signed `Envelope` of EnvelopeContent::ReadState to the IC. 
The method that is added is similar to the already existing `wait(..)` method but also takes in the signed request.
=> feat: add pre signed read state call wait

.github/workflows/e2e.yml, .github/workflows/fmt.yml, .github/workflows/ic-ref.yml, .github/workflows/lint.yml, .github/workflows/netlify.yml, .github/workflows/release.yml, .github/workflows/shellcheck.yml, .github/workflows/test.yml
Also updated github actions versions due to Node deprecations.
=> chore: update ic-ref test to use dfx 0.16.1; update gh action versions

CHANGELOG.md, ic-utils/src/interfaces/management_canister/builders.rs, ref-tests/tests/ic-ref.rs
Tried to add `--skip-pre-upgrade` to dfx and noticed it doesn't work. Turns out the type is wrong
Not tested.
=> fix!: change type of skip_pre_upgrade

CHANGELOG.md, ic-utils/src/interfaces/management_canister.rs, icx/src/main.rs
This adds the ECDSA and Bitcoin functions to MgmtMethod for completeness, but no wrapper functions in ManagementCanister because only canisters can call these functions.
=> feat: Add unsupported methods to MgmtMethod

CHANGELOG.md, ic-utils/src/interfaces/management_canister.rs, icx/src/main.rs
This PR adds a new `MgmtMethod::FetchCanisterLogs` item to the management canister methods enum with a corresponding `ManagementCanister::fetch_canister_logs()` wrapper and a `FetchCanisterLogsResponse` as a result type. Note that this method can only be called in non-replicated mode.
Regular CI.
=> feat: [IC-272] add fetch_canister_logs method to management canister

CHANGELOG.md, ic-agent/src/agent/builder.rs, ic-agent/src/agent/mod.rs, ic-agent/src/agent/response_authentication.rs, ic-agent/src/lib.rs, ic-utils/src/call.rs, ic-utils/src/canister.rs, ref-tests/src/utils.rs, ref-tests/tests/ic-ref.rs
This expands the timestamp check used for subnet keys to any certificate verification. 
The tests were also updated to use 4943 as the default port, and to be compatible with being run twice against the same replica.
=> fix: check read_state timestamps

CHANGELOG.md, ic-utils/src/interfaces/management_canister.rs, icx/src/main.rs
This adds the node_metrics_history function to MgmtMethod as an unsupported function, and adds wrappers for bitcoin_get_balance_query and bitcoin_get_utxos_query, which were incorrectly assumed as unsupported like the non-query counterparts.
=> feat: Add metrics method and bitcoin query wrappers

.github/workflows/lint.yml
This PR changes the cargo clippy setup to use [`cargo-hack`](https://github.com/taiki-e/cargo-hack), to check each feature individually instead of only the default features or only the full set of features. Two commands are used so that features enabled in dev-dependencies don't leak into checking normal builds.
=> chore: Check features individually

CHANGELOG.md, ic-agent/Cargo.toml, ic-agent/src/agent/status.rs
This is a breaking change.
https://github.com/dfinity/agent-rs/pull/499 added the CandidType, Serialize, and Deserialized traits to Status, in support of `dfx ping` to output json.
However, Status isn't really appropriate for any of these.  The `values` map contains every field in the status.  But the other fields are populated during cbor deserialization.  It's true that technically, you could serialize a Status and then deserialize it, even to and from candid.  But when formatted to json, with the default serializer, a Status might look like this:
```
{
"impl_hash": "a380266e4b6977b7cce447aa5f784efdba0bb45820d51f39b9e7908f7fbb1aa1",
"replica_health_status": "healthy",
"root_key": [ 48, 129, 130 ],
"values": {
"certified_height": {
"Integer": 948674
},
"ic_api_version": {
"String": …
```
=> fix: Revert: Add serialization traits to Status

.github/workflows/e2e.yml, ic-utils/src/interfaces/management_canister.rs, icx/src/main.rs
In short, the effectice_canister_id should be `aaaaa-aa` (management canister).
The same issue was found in dfx: https://github.com/dfinity/sdk/pull/3660
So apply the same fix.
The API was added without any tests. We may add it in a later PR.
The sdk PR above gives somewhat confidence.
=> fix: effective_canister_id of bitcoin queries

CHANGELOG.md, ic-agent/src/agent/status.rs
Added a comma and newline in between fields.  
Fixes https://dfinity.atlassian.net/browse/SDK-1457
Tested locally with a modified dfx
```
$ cargo run ping ic
{
"ic_api_version": "0.18.0",
"replica_health_status": "healthy",
"root_key": [48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 129, 76, 14, 110, 199, 31, 171, 88, 59, 8, 189, 129, 55, 60, 37, 92, 60, 55, 27, 46, 132, 134, 60, 152, 164, 241, 224, 139, 116, 35, 93, 20, 251, 93, 156, 12, 213, 70, 217, 104, 95, 145, 58, 12, 11, 44, 197, 52, 21, 131, 191, 75, 67, 146, 228, 103, 219, 150, 214, 91, 155, 180, 203, 113, 113, 18, 248, 71, 46, 13, 90, 77, 20, 80, 95, 253, 116, 132, 176, 18, 145, 9, 28, 95, 135, 185, 136, 131, 70, 63, 152, 9, 26, 11, 170, 174] …
```
=> fix: fmt::Display output for Status is now valid JSON

CHANGELOG.md, ic-agent/src/agent/agent_test.rs, ic-agent/src/agent/mod.rs
* Added `QueryBuilder::call_with_verification()` and `QueryBuilder::call_without_verification()` which always/never verify query signatures
regardless the Agent level configuration from `AgentBuilder::with_verify_query_signatures`.
Part of SDK-1505
The [sdk PR](https://github.com/dfinity/sdk/pull/3668) is using the new method `call_without_verification()` which was tested in the sdk e2e tests.
=> feat: add call_with_verification and call_without_verification methods to QueryBuilder

CHANGELOG.md, ic-utils/src/interfaces/wallet.rs
New replica versions report it as CanisterError instead; removing the check entirely is easier than doing this again in the future.
=> fix: Remove `DestinationInvalid` check from `WalletCanister::from_canister`

CHANGELOG.md, ic-agent/src/agent/agent_test.rs, ic-agent/src/agent/mod.rs
Following the [spec](https://internetcomputer.org/docs/current/references/ic-interface-spec#http-read-state), it would make sense to split `fn fetch_api_boundary_nodes(effective_canister_id)` into two functions:
```
pub async fn fetch_api_boundary_nodes_by_canister_id(canister_id)
pub async fn fetch_api_boundary_nodes_by_subnet_id(subnet_id)
```
1. Testing against mainnent is not yet possible, [this](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/18438) MR needs to be released.
2. Functions were tested in `system-tests` with respective `canister_id/subnet_id`.
=> feat: remove `effective_canister_id` from `fn fetch_api_boundary_nodes()` signature

CHANGELOG.md, ic-agent/src/agent/http_transport/hyper_transport.rs, ic-agent/src/agent/http_transport/reqwest_transport.rs
Current design of the `ReqwestTransport` and `HyperTransport` is based on the single ownership of the `RouteProvider` trait object. This has several downsides: 
- One can't create multiple `agent` instances sharing the same `RouteProvider` instance
- One can't modify `RouteProvider` state after an `agent` is created, e.g.:
```
let route_provider = SomeRouteProvider::new();
route_provider.run().await;
let transport = ReqwestTransport::create_with_client_route(Box::new(route_provider), client).unwrap();
let agent = Agent::builder().with_transport(transport).build().unwrap("");
... // do stuff with agent
route_provider.stop().await; // gracefully stop (impossible)
```
Using `Arc` instead of `Box` should allow for shared ownership of `RouteProvider` and rectify the  aforementioned …
=> feat: ReqwestTransport and HyperTransport allow for shared RouteProvider ownership

CHANGELOG.md, ic-utils/src/interfaces/management_canister.rs, ic-utils/src/interfaces/management_canister/attributes.rs, ic-utils/src/interfaces/management_canister/builders.rs, ic-utils/src/interfaces/wallet.rs, ref-tests/tests/ic-ref.rs, ref-tests/tests/integration.rs
This add a new `wasm_memory_field` to canister settings.
Both canister creation and updating of canister settings now have the new field.
Part of https://dfinity.atlassian.net/browse/SDK-1588
Added new tests.
=> feat: Add `wasm_memory_limit` to canister settings

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/agent_config.rs, ic-agent/src/agent/agent_test.rs, ic-agent/src/agent/builder.rs, ic-agent/src/agent/http_transport/hyper_transport.rs, ic-agent/src/agent/http_transport/reqwest_transport.rs, ic-agent/src/agent/mod.rs, ic-agent/src/lib.rs, ic-agent/src/util.rs, ic-utils/Cargo.toml
ManagementCanister::install currently does not work for very large modules due to hitting 429 after the first fifty chunks. This PR fixes that in two ways: limiting concurrent requests to 50 via semaphore, and retrying any 429s that slip through.
=> feat: client-side ratelimiting and auto-retrying 429s

.github/workflows/e2e.yml, .github/workflows/release.yml, .github/workflows/shellcheck.yml
macos-latest was recently switched to macos-14-arm.
We need the x86-64 platform.
=> ci: macos-12

Cargo.lock
=> chore: Update h2 and rustls

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml
We are upgrading reqwest across the whole main repository. Modules that depend on `ic-agent` can cause a dependency conflict.
`cargo test`
=> chore: bump reqwest version

ic-agent/src/agent/mod.rs
Currently we reject certificates that were signed too far in the past; this PR additionally rejects certificates signed too far in the future. Future timestamps indicate a clock mismatch and a timestamp that seems in the future may actually be too far in the past.
=> fix: Deny certs with timestamps in the future as well as the past

CHANGELOG.md, ic-agent/src/agent/agent_test.rs, ic-agent/src/agent/http_transport/hyper_transport.rs, ic-agent/src/agent/http_transport/reqwest_transport.rs
[RouteProvider](https://github.com/dfinity/agent-rs/blob/d3db617c3698e7ee1a4a3074c495ff063b91bab1/ic-agent/src/agent/http_transport/route_provider.rs#L17) which is used to dynamically retrieve routing URLs for HTTP calls, can potentially return unhealthy URLs. This will be especially acute once API Boundary Node decentralization feature is released, as node providers will be the ones responsible for API nodes maintenance.
If an HTTP request fails on a URL with a network-related error (e.g., host unreachable, connection timeout, connection refused), then this request can be safely retried by using an alternative routing URL, generated by the `RouteProvider`. This retrying policy aims at improving user experience.
Please describe the tests that you ran to verify your changes. Provide …
=> feat: introduce http request retries on tcp failures

CHANGELOG.md, ic-utils/src/interfaces/management_canister.rs, ic-utils/src/interfaces/management_canister/builders.rs, ic-utils/src/interfaces/wallet.rs, ref-tests/tests/ic-ref.rs, ref-tests/tests/integration.rs
Adds support for the new `log_visibility` setting in canister settings, both when creating a canister and when updating the settings.
Part of [SDK-1543](https://dfinity.atlassian.net/browse/SDK-1543)
Added tests.
[SDK-1543]: https://dfinity.atlassian.net/browse/SDK-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add `log_visibility` to canister settings

Cargo.lock, ic-agent/Cargo.toml
Now all dependencies are updated to their latest major versions.
=> chore: update ic-verify-bls-signature to v0.5

CHANGELOG.md, ic-agent/src/agent/http_transport/hyper_transport.rs
Bug fix:
The hyper transport has a bug where it doesn't include the `api/v2` prefix for the endpoint when sending `read_state` requests.
Ran E2E test on the replica with hyper transport.
=> fix(hyper-transport): Add `api/v2` prefix to read_state requests for hyper transport

CHANGELOG.md, ic-utils/src/interfaces/management_canister.rs, ref-tests/tests/ic-ref.rs
This PR adds a new `AllowedViewers` variant to `LogVisibility` enum of the management canister API.
Fixes # (issue): SDK-1800
Regular CI.
=> feat: add AllowedViewers to LogVisibility enum

CHANGELOG.md, ic-agent/Cargo.toml, ic-agent/src/agent/agent_config.rs, ic-agent/src/agent/agent_test.rs, ic-agent/src/agent/builder.rs, ic-agent/src/agent/http_transport/reqwest_transport.rs, ic-agent/src/agent/mod.rs, ref-tests/Cargo.toml, ref-tests/src/utils.rs
This PR makes the agent submit all ingress messages to the synchronous update call endpoint `/api/v3/.../call` for all update calls by default. The endpoint is now live on mainnet.
All update calls tests have been updated to target the v3 endpoint.
=> feat: route all update calls to synchronous v3 endpoint

CHANGELOG.md, Cargo.lock, ic-agent/Cargo.toml, ic-agent/src/agent/agent_config.rs, ic-agent/src/agent/builder.rs, ic-agent/src/agent/mod.rs
ic-gateway was broken by #586, this provides a middle ground for them.
=> feat: Add HTTP middleware for Transport replacement

CHANGELOG.md, Cargo.lock, ic-agent/src/agent/mod.rs, ic-transport-types/Cargo.toml, ic-transport-types/src/lib.rs, ic-transport-types/src/signed.rs
This PR adds two missing functions to close the loop around non-`Identity` forms of signing - the ability to construct `EnvelopeContent` using the agent's autofill logic, and the ability to encode `Envelope` to the format expected by `update_signed`.
=> feat: Add encoding functions for external signing

CHANGELOG.md, ic-agent/src/agent/mod.rs
Currently HTTP 429 may be retried indefinitely. This PR limits the retries, so that hiccups are still smoothed over but real errors are properly raised.
=> fix: Limit 429 retries

CHANGELOG.md, ic-agent/src/agent/agent_config.rs, ic-agent/src/agent/agent_test.rs, ic-agent/src/agent/builder.rs, ic-agent/src/agent/mod.rs
Decrease the ingress expiry default.
Adding a message to be processed takes the order of seconds. We can expiry messages more aggressively.
=> fix: decrease the ingress expiry default to 3 min

CHANGELOG.md, ic-agent/src/agent/mod.rs, ic-agent/src/agent/response_authentication.rs, ic-utils/src/call.rs, ic-utils/src/canister.rs, icx/src/main.rs, ref-tests/tests/ic-ref.rs, ref-tests/tests/integration.rs
This changes the interface of the lower-level functions like request_status_signed, but leaves call_and_wait's interface alone.
=> feat: provide certificate for update calls

ic-utils/src/interfaces/management_canister.rs, icx/src/main.rs
Since this cannot be called by canisters outside the bitcoin canister interface, this does not include an implementation.
=> feat: Add BitcoinGetBlockHeaders to MgmtMethod

ic-agent/Cargo.toml, ic-agent/src/agent/agent_config.rs, ic-agent/src/agent/builder.rs, ic-agent/src/agent/mod.rs, ic-agent/src/agent/route_provider.rs, ic-agent/src/agent/route_provider/dynamic_routing/dynamic_route_provider.rs, ic-agent/src/agent/route_provider/dynamic_routing/health_check.rs, ic-agent/src/agent/route_provider/dynamic_routing/mod.rs, ic-agent/src/agent/route_provider/dynamic_routing/node.rs, ic-agent/src/agent/route_provider/dynamic_routing/nodes_fetch.rs, ic-agent/src/agent/route_provider/dynamic_routing/snapshot/latency_based_routing.rs, ic-agent/src/agent/route_provider/dynamic_routing/snapshot/routing_snapshot.rs, ic-agent/src/agent/route_provider/dynamic_routing/test_utils.rs, ic-agent/src/lib.rs, ic-agent/src/util.rs
This PR sets the final interface of the dynamic routing feature as a wrapper around the draft implementation, since work on the final implementation has stalled. The draft implementation may or may not be replaced in the future.
=> feat: dynamic routing mvp

Cargo.toml, ref-tests/tests/ic-ref.rs, rust-toolchain.toml
rust-analyzer no longer supports 1.77 and below.
=> chore: Update MSRV to 1.78

CHANGELOG.md, Cargo.lock, Cargo.toml
The latest ic-certification version is 3. This repo currently uses 2.6. For compatibility with libraries that have already updated to version 3, we bump the version.
=> chore: bump ic-certification 

ic-utils/src/interfaces/management_canister.rs, ic-utils/src/interfaces/management_canister/builders.rs
The current docs indicate that it is a distance from 0; this clarifies that it is a distance from `wasm_memory_limit`.
=> chore: clarify wasm threshold docs

.github/workflows/e2e.yml, CHANGELOG.md, ic-utils/src/interfaces/management_canister.rs, icx/src/main.rs
Added `CanisterInfo` to `MgmtMethod`. 
This addresses the issue that `dfx canister call aaaaa-aa canister_info '(record {canister_id=principal"<canister-id>"; num_requested_changes=opt 20;})' --wallet <wallet-id> --ic` failed with `Attempted to call an unsupported management canister method: canister_info`.
=> feat: Add `CanisterInfo`.

CHANGELOG.md, ic-agent/src/agent/route_provider.rs, ic-agent/src/agent/route_provider/dynamic_routing/dynamic_route_provider.rs, ic-agent/src/agent/route_provider/dynamic_routing/snapshot/latency_based_routing.rs, ic-agent/src/agent/route_provider/dynamic_routing/snapshot/round_robin_routing.rs, ic-agent/src/agent/route_provider/dynamic_routing/snapshot/routing_snapshot.rs
`RouteProvider` trait is extended with a method to get useful metrics about the total number of routes and healthy number of routes.
```
/// Returns statistics about the total number of existing routes and the number of healthy routes.
fn routes_stats(&self) -> RoutesStats;
```
Unit tests were extended accordingly.
=> chore: extend `RouteProvider` trait with routes_stats()

CHANGELOG.md, ic-agent/src/agent/builder.rs
`AgentBuilder` method `with_background_dynamic_routing` is `async` for no reason.
Reported [on the forum](https://forum.dfinity.org/t/boundary-node-roadmap/15562/97)
not tested
=> fix: AgentBuilder::with_background_dynamic_routing is async

CHANGELOG.md
The CHANGELOG was mistakenly updated in the wrong section. The notes should have been added under 'Unreleased' instead of modifying the previous release.
=> fix: CHANGELOG.md unreleased notes

CHANGELOG.md, Cargo.lock, Cargo.toml, ic-agent/Cargo.toml, ic-agent/src/agent/response_authentication.rs, ic-agent/src/agent/route_provider/dynamic_routing/mod.rs, rust-toolchain.toml
- Release `0.42.0` with changes about using ic-management-canister-types in ic-utils.
- Bump MSRV from `1.78.0` to `1.85.0` as the feature `edition2024` is required during running `cargo publish`.
=> chore: Release 0.42.0

CHANGELOG.md, Cargo.lock, Cargo.toml
This release will make the snapshot upload/download feature in `dfx` work with the [updated](https://github.com/dfinity/ic/pull/6363) replica.
=> chore: release v0.43.0

CHANGELOG.md, Cargo.lock, Cargo.toml
This release will enable downstream projects like icp-cli to utilize the new IC environment variables feature.
=> chore: release v0.44.0

CHANGELOG.md, ic-agent/src/agent/mod.rs, ic-agent/src/agent/response_authentication.rs, ref-tests/tests/ic-ref.rs
Added `read_state_subnet_canister_ranges` which can query the canister id ranges for a given subnet.
[SDK-2212](https://dfinity.atlassian.net/browse/SDK-2212)
New ic-ref test added.
[SDK-2212]: https://dfinity.atlassian.net/browse/SDK-2212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add `read_state_subnet_canister_ranges`

ic-agent/src/agent/mod.rs
=> fix: Verify canister ranges for all subnets
