ic-utils/src/interfaces/management_canister.rs
ic-utils/src/interfaces/management_canister/attributes.rs
ref-tests/tests/ic-ref.rs

And added a test for memory_allocation and compute_allocation.

fix: use candid Natural instead of fixed bytes numbers in install

---

ic-agent/src/agent/builder.rs
ic-agent/src/agent/mod.rs
ic-utils/src/canister.rs
ic-utils/src/interfaces/wallet.rs

Fixes https://github.com/dfinity/agent-rs/issues/73

feat: replace all ToString type parameter constraints with Into<String>.

---

ic-agent/src/hash_tree.rs
ic-agent/src/hash_tree/hash_tree_tests.rs
ic-agent/src/lib.rs

It understands labels and can lookup paths and return blobs of those
paths, if found.

feat: add a HashTree type for the certificate state

---

.github/workflows/ic-ref.yml
ic-utils/src/canister.rs
ref-tests/src/utils.rs
ref-tests/tests/ic-ref.rs
ref-tests/tests/integration.rs

feat: Updates ic-ref to 0.14

---

.github/workflows/ic-ref.yml
ic-agent/Cargo.toml
ic-utils/Cargo.toml
ic-utils/src/interfaces/wallet.rs
icx/Cargo.toml
ref-tests/Cargo.toml
ref-tests/src/utils.rs
ref-tests/tests/integration.rs

depends on: https://github.com/dfinity/wallet-rs/pull/38
This just updates the interface and adds a bunch of tests.

feat: update wallet interface for wallet create wallet

---

ic-agent/src/agent/agent_error.rs

The replica often returns HttpError in which the content type is empty but the content is actually UTF-8 String. Before, people had to manually convert the byte array into String to see the meaningful content. With this fix, the content will always be parsed whatever the content type is. 
We should also check the replica implementation why the content type was not set correctly.

fix: always parse HttpError content as UTF-8 whatever the content type

---

.github/workflows/ic-ref.yml
ic-agent/src/agent/agent_error.rs
ic-utils/src/interfaces/wallet.rs
ref-tests/src/utils.rs
ref-tests/tests/integration.rs

depends on https://github.com/dfinity/wallet-rs/pull/41

feat: add results in wallet calls

---

ic-utils/src/interfaces/http_request.rs
icx-http-server/src/main.rs

Implements https://github.com/dfinity/agent-rs/issues/138
Required for https://github.com/dfinity/sdk/issues/1570 (PR: https://github.com/dfinity/sdk/pull/1573)

feat: Update icx-http-server to support latest HTTP Query proposal

---

.github/workflows/ic-ref.yml
ic-agent/src/agent/agent_config.rs
ic-agent/src/agent/agent_test.rs
ic-agent/src/agent/builder.rs
ic-agent/src/agent/http_transport.rs
ic-agent/src/agent/mod.rs
ic-agent/src/agent/replica_api.rs
ic-agent/src/agent/response.rs
ic-agent/src/agent/response_authentication.rs
ic-agent/src/lib.rs
ic-utils/Cargo.toml
ic-utils/src/call.rs
ic-utils/src/canister.rs
ic-utils/src/interfaces/management_canister.rs
icx/Cargo.toml
icx/src/main.rs
ref-tests/src/utils.rs
ref-tests/tests/ic-ref.rs

feat: initial api/v2 support

---

ic-agent/Cargo.toml
ic-identity-hsm/Cargo.toml
ic-utils/Cargo.toml
icx-proxy/Cargo.toml
icx-proxy/README.md
icx-proxy/src/main.rs
icx/Cargo.toml

chore: add metadata and get crates ready for publishing

---

icx-proxy/src/config/canister_dns_config.rs

Fixes https://github.com/dfinity/agent-rs/issues/153

fix: [icx-proxy] Sort aliases from longest to shortest

---

ic-agent/Cargo.toml
ic-agent/src/agent/mod.rs
ic-agent/src/lib.rs
ic-utils/Cargo.toml
ic-utils/src/call.rs
ic-utils/src/canister.rs
ic-utils/src/interfaces/management_canister.rs
ic-utils/src/interfaces/wallet.rs
icx-proxy/Cargo.toml
icx/Cargo.toml
icx/src/main.rs
ref-tests/Cargo.toml
ref-tests/src/utils.rs

This way the waiter is not blocking on async flow.

refactor: use the new (improved) async version of delay

---

icx-proxy/src/main.rs

Those messages are meant to be user visible, and can actually happen
on correct calls. We should show the user the message so they could see
what failed. Currently they only get 500 Internal Server Error, which
is not very useful.
Note that a savvy user could use dfx to get the reject message so this
does not reveal more information than what is already available. It
makes it more accessible.

feat: show the reject code and message on replica error

---

ic-types/src/principal.rs

This is yak shaving to allow ic_types to support no_std feature. This would
make ic_types smaller and faster. Right now it's kind of an optimization
and a quality of life refactor.

refactor: remove Vec from principal and use arrays

---

ic-types/src/principal.rs

Also some minor comment cleanup

feat: make more `Principal` functions `const` (#190)

---

ic-types/src/principal.rs
ic-utils/src/canister.rs

Fixes #193.
Switched from `ExternalError` to `dyn Error` in CanisterBuilder.

refactor: remove `PrincipalBufferError` (#193)

---

Cargo.lock
Cargo.toml
README.md
ic-agent/Cargo.toml
zzz-release/Cargo.toml
zzz-release/src/main.rs

It updates the versions, create a commit, and show which packages need to be published in what order.

chore: add a zzz-release binary that update the version of crates

---

Cargo.lock
ic-agent/Cargo.toml
ic-types/Cargo.toml
ic-utils/Cargo.toml

icx: 0.2.2
ic-agent: 0.5.1 => 0.5.2
icx-proxy: 0.3.1
ic-identity-hsm: 0.3.2
ic-utils: 0.3.2 => 0.3.3
ic-types: 0.1.4 => 0.1.5

chore: release of ic-agent

---

Cargo.lock
ic-agent/Cargo.toml
ic-asset/Cargo.toml
ic-utils/Cargo.toml
icx-asset/Cargo.toml
icx/Cargo.toml
ref-tests/Cargo.toml

Companion sdk PR for verification: https://github.com/dfinity/sdk/pull/1771

chore: upgrade to candid 0.7.4, ic-types 0.2.1

---

.github/workflows/provision-darwin.sh
.github/workflows/provision-linux.sh
Cargo.lock
e2e/bash/icx.bash
ic-agent/Cargo.toml
ic-agent/src/agent/signed.rs
ic-asset/Cargo.toml
icx-asset/Cargo.toml
icx/README.md
icx/src/main.rs

The implementation has been manually tested with the example in icx README.
We still lack of a test framework for cli package.

feat: icx sign/send with new ic-agent API

---

Cargo.lock
README.md

Also updated the release process documentation to update it in the future.

chore: Cargo.lock for release

---

icx-asset/Cargo.toml
icx-cert/Cargo.toml
icx-cert/README.md

https://dfinity.atlassian.net/browse/SDK-79

chore: Add metadata to icx-cert and icx-asset so that they can be published

---

icx-asset/src/commands/list.rs
icx-asset/src/commands/mod.rs
icx-asset/src/commands/sync.rs
icx-asset/src/main.rs
icx-asset/src/support.rs

Make a commands package so that main.rs doesn't grow too large.

refactor: icx-asset commands package

---

Cargo.lock
ic-agent/Cargo.toml
ic-asset/Cargo.toml
ic-identity-hsm/Cargo.toml
ic-utils/Cargo.toml
icx-asset/Cargo.toml
icx-cert/Cargo.toml
icx-proxy/Cargo.toml
icx/Cargo.toml

Also updated ic-types to 0.2.2

chore: release agent-rs 0.8.0 and friends

---

ic-agent/CHANGELOG.md
ic-agent/src/agent/status.rs

feat: report replica_health_status in Status

---

CHANGELOG.md
Cargo.lock
ic-agent/Cargo.toml
ic-asset/Cargo.toml
ic-identity-hsm/Cargo.toml
ic-utils/Cargo.toml
icx-asset/Cargo.toml
icx-cert/Cargo.toml
icx/Cargo.toml

chore: rust agent 0.11.1

---

Cargo.lock
icx-asset/Cargo.toml
icx-cert/Cargo.toml
icx/Cargo.toml

chore: Update clap to 3.0

---

CHANGELOG.md
ic-utils/src/interfaces/management_canister/builders.rs
ref-tests/src/utils.rs
ref-tests/tests/ic-ref.rs

chore: cycles are now u128 instead of u64

---

CHANGELOG.md
Cargo.lock
ic-agent/Cargo.toml
ic-asset/Cargo.toml
ic-identity-hsm/Cargo.toml
ic-utils/Cargo.toml
icx-asset/Cargo.toml
icx-cert/Cargo.toml
icx/Cargo.toml

There were breaking changes since 0.12.1

chore: release rust agent 0.13.0

---

.github/workflows/release.yml

Fixes the release pipeline being broken.

chore: Switch to using dfinity's musl action

---

Cargo.lock
icx-asset/src/main.rs
icx/src/main.rs

Fixes the new `clap` warning and updates `flate2`.

fix: Fix clap deprecation

---

CHANGELOG.md
Cargo.lock
ic-agent/Cargo.toml
ic-asset/Cargo.toml
ic-identity-hsm/Cargo.toml
ic-utils/Cargo.toml
icx-asset/Cargo.toml
icx-cert/Cargo.toml
icx/Cargo.toml

Also, we missed some changelog entries along the way.

chore: release agent-rs 0.16.0

---

.github/CODEOWNERS

CODEOWNERS needs a pattern too

chore: add pattern to CODEOWNERS

---

.github/workflows/e2e.yml
e2e/bash/icx-asset-upload.bash
e2e/bash/icx-asset.bash
e2e/bash/icx.bash

Also renamed the workflow to e2e, and made it run icx-asset-upload.bash
It does not yet run icx.bash, because I couldn't get it to work

test: run e2e tests against newer versions of dfx

---

.github/workflows/e2e.yml
.github/workflows/fmt.yml
.github/workflows/ic-ref.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
Cargo.lock
ic-agent/Cargo.toml
ic-agent/src/request_id/mod.rs
ic-asset/Cargo.toml
ic-identity-hsm/Cargo.toml
ic-utils/Cargo.toml
icx-asset/Cargo.toml
icx-asset/src/commands/list.rs
icx-cert/Cargo.toml
icx/Cargo.toml
rust-toolchain.toml

Mirroring the update in replica eea989b.

chore: update Rust to 1.60.0

---

CHANGELOG.md
ic-utils/src/interfaces/management_canister/builders.rs
ref-tests/tests/ic-ref.rs

feat: specified_id in provisional_create_canister_with_cycles

---

Cargo.lock

chore: Update tempfile

---

ic-agent/src/agent/agent_error.rs
ic-agent/src/agent/response.rs
ic-agent/src/agent/response_authentication.rs
ref-tests/tests/integration.rs

This PR cleans up imports introduced in PR #422 that were found after the PR was merged. See @rumenov's last review comments added after the merge.
Fixes #428 
Cargo test.

chore: Clean up imports introduced in PR #422

---

CHANGELOG.md

chore: release v0.25.0

---

.github/workflows/e2e.yml
.github/workflows/fmt.yml
.github/workflows/ic-ref.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
Cargo.toml
rust-toolchain.toml

Similar to https://github.com/dfinity/cdk-rs/pull/421

chore: revert MSRV

---

.github/workflows/ic-ref.yml
CHANGELOG.md
ic-agent/src/agent/http_transport/hyper_transport.rs
ic-agent/src/agent/http_transport/reqwest_transport.rs
ic-agent/src/agent/mod.rs
ic-agent/src/agent/response_authentication.rs
ic-transport-types/src/lib.rs
ic-transport-types/src/request_id.rs
ref-tests/tests/ic-ref.rs

This PR implements the new subnet metrics API in the state tree, as well as the new underlying subnet-ID-based state tree request endpoint.

feat: subnet metrics

---

CHANGELOG.md
ic-utils/src/interfaces/management_canister.rs

feat: Add query stats to canister status

---

Cargo.lock
Cargo.toml

chore: bump ic-certification

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 

chore: release v0.32.0

---

ic-utils/README.md

chore: remove dead link

---

ic-agent/src/agent/mod.rs

Fixes a typo in the description of `UpdateBuilder::new`.
It hasn't been tested.

fix: fix description of UpdateBuilder::new

---

CHANGELOG.md
Cargo.lock
Cargo.toml

chore: Release 0.37.1

---

CHANGELOG.md
ic-utils/src/interfaces/management_canister/builders.rs

Match the new replica's management canister API.

feat!: Lowercase `WasmMemoryPersistence`

---

ic-agent/src/agent/route_provider/dynamic_routing/dynamic_route_provider.rs
ic-agent/src/agent/route_provider/dynamic_routing/health_check.rs
ic-agent/src/agent/route_provider/dynamic_routing/mod.rs
ic-agent/src/agent/route_provider/dynamic_routing/snapshot/latency_based_routing.rs
ic-agent/src/lib.rs
ic-identity-hsm/src/lib.rs

1. Extended the documentation for the Agent module to include details on dynamic routing.
2. Updated the main example of Agent usage: more illustrative and functional one.
Only documentation changes.

docs: extend `DynamicRouteProvider` documentation
